"""Export a recipe as a standalone Scrapy project (zip).

The generated project depends on the `scrapy-awesome` package for the engine (stealth tiers,
extraction, coercion) but nothing else: no server, no UI, no LLM. `scrapy crawl recipe -O out.jsonl`
runs the exact same `RecipeSpider` the app runs, from the embedded `recipe.json`.
"""

from __future__ import annotations

import io
import json
import zipfile
from pathlib import Path

from scrapy_awesome import __version__
from scrapy_awesome.recipe.models import Recipe

_SCRAPY_CFG = """[settings]
default = {pkg}.settings

[deploy]
project = {pkg}
"""

_SETTINGS = '''"""Scrapy settings generated by scrapy-awesome {version}.

Everything the app applies to a run (stealth middleware, Playwright/Patchright handler, escalation,
throttling, HTTP cache) comes from `scrapy_awesome.crawl.settings.build_settings`, so this project
crawls exactly like the app did. Edit the recipe in recipe.json.
"""

from pathlib import Path

from scrapy_awesome.crawl.settings import build_settings
from scrapy_awesome.recipe.io import load_recipe

HERE = Path(__file__).resolve().parent
RECIPE = load_recipe(HERE / "recipe.json")
RUN_DIR = HERE.parent / "runs" / "latest"
RUN_DIR.mkdir(parents=True, exist_ok=True)

_settings = build_settings(
    RECIPE,
    run_dir=RUN_DIR,
    httpcache_dir=HERE.parent / ".httpcache",
    jobdir=None,  # set to a path to make the crawl resumable
    obey_robots={obey_robots},
    log_level="INFO",
)
globals().update(_settings)

BOT_NAME = "{pkg}"
SPIDER_MODULES = ["{pkg}.spiders"]
NEWSPIDER_MODULE = "{pkg}.spiders"
'''

_SPIDER = '''"""`scrapy crawl recipe -O ../out.jsonl` — runs the recipe with scrapy-awesome's RecipeSpider."""

from pathlib import Path

from scrapy_awesome.crawl.spider import RecipeSpider as _RecipeSpider

HERE = Path(__file__).resolve().parent.parent


class RecipeSpider(_RecipeSpider):
    name = "recipe"

    def __init__(self, **kwargs):
        run_dir = HERE.parent / "runs" / "latest"
        super().__init__(
            run_id="local",
            run_dir=str(run_dir),
            recipe_path=str(HERE / "recipe.json"),
            **kwargs,
        )
'''

_README = """# {name} — standalone Scrapy project

Generated by scrapy-awesome {version}. Requires Python ≥ 3.12.

```bash
python -m venv .venv && . .venv/bin/activate      # (Windows: .venv\\Scripts\\activate)
pip install "scrapy-awesome=={version}"           # engine only; no server/UI needed
patchright install chromium                        # only if the recipe needs the interactive tier
scrapy crawl recipe -O out.jsonl                   # or -O out.csv / out.json
```

* Edit `{pkg}/recipe.json` to change fields, pagination, limits (same format as the app).
* Events are written to `runs/latest/events.jsonl`; items also go to `runs/latest/items.jsonl`.
* Set `jobdir` in `{pkg}/settings.py` to make crawls resumable.
* The stealth *browser* tier uses your installed Google Chrome; the *interactive* tier uses
  Patchright's Chromium.
"""


def _pkg_name(recipe: Recipe) -> str:
    base = "".join(ch if ch.isalnum() else "_" for ch in recipe.name.lower()).strip("_") or "recipe"
    if base[0].isdigit():
        base = "r_" + base
    return base[:40]


def build_zip(recipe: Recipe, *, obey_robots: bool = True) -> bytes:
    pkg = _pkg_name(recipe)
    root = f"{pkg}_scrapy"
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr(f"{root}/scrapy.cfg", _SCRAPY_CFG.format(pkg=pkg))
        z.writestr(
            f"{root}/README.md", _README.format(name=recipe.name, version=__version__, pkg=pkg)
        )
        z.writestr(f"{root}/requirements.txt", f"scrapy-awesome=={__version__}\n")
        z.writestr(f"{root}/{pkg}/__init__.py", "")
        z.writestr(
            f"{root}/{pkg}/settings.py",
            _SETTINGS.format(version=__version__, pkg=pkg, obey_robots=obey_robots),
        )
        z.writestr(f"{root}/{pkg}/recipe.json", json.dumps(recipe.to_dict(), indent=2))
        z.writestr(f"{root}/{pkg}/spiders/__init__.py", "")
        z.writestr(f"{root}/{pkg}/spiders/recipe_spider.py", _SPIDER)
        z.writestr(f"{root}/runs/.gitkeep", "")
    return buf.getvalue()


def write_zip(recipe: Recipe, dest: Path, *, obey_robots: bool = True) -> Path:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(build_zip(recipe, obey_robots=obey_robots))
    return dest
